In [1]:
import math
import numpy as np
from rotations.quaternions import Quaternion
import rotations.representations as rot

In [2]:
phi = math.pi * 1/3
theta = math.pi * 1/4
psy = math.pi * 4/5
print(phi, theta, psy)

1.0471975511965976 0.7853981633974483 2.5132741228718345


In [3]:
a = rot.euler2a(phi, theta, psy)
print(a)

[[-0.5720614  -0.78931233  0.22300626]
 [ 0.41562694 -0.04456501  0.90844274]
 [-0.70710678  0.61237244  0.35355339]]


In [4]:
axis, angle = rot.axis_angle(a)
print(axis, angle)
r = rot.rodrigez(axis, angle)
print(r)

[-0.19092782+0.j  0.59980504+0.j  0.77703313+0.j] 2.254329653103487
[[-0.5720614 +0.j -0.78931233+0.j  0.22300626+0.j]
 [ 0.41562694+0.j -0.04456501+0.j  0.90844274+0.j]
 [-0.70710678+0.j  0.61237244+0.j  0.35355339+0.j]]


In [5]:
print(rot.a2euler(a))
print(phi, theta, psy)

(1.0471975511965976, 0.7853981633974482, 2.5132741228718345)
1.0471975511965976 0.7853981633974483 2.5132741228718345


In [6]:
q = Quaternion.from_axis_angle(axis, angle)
print(q)

Quaternion((-0.1724458010246311+0j)i + (0.5417432513768276+0j)j + (0.7018154679091264+0j)k + (0.4292222551314542+0j))


In [7]:
axis_n, angle_n = q.to_axis_angle()
print(axis_n, angle_n)

[-0.19092782+0.j  0.59980504+0.j  0.77703313+0.j] 2.254329653103487


/home/nikola/geom2/rotations/quaternions.py:107: ComplexWarning: Casting complex values to real discards the imaginary part
  angle = 2 * math.acos(self.w)
/home/nikola/geom2/rotations/quaternions.py:108: ComplexWarning: Casting complex values to real discards the imaginary part
  if math.isclose(math.fabs(self.w), 1):  # identity
